FILES = \
    core.py  __init__.py  dequeue.py  Subprocess.py  TaskQueue.py Version.py \
    RWLock.py promise.py Scheduler.py processor.py gate.py flag.py

LIB_DIR = $(BUILD_DIR)/pythreader

build: $(LIB_DIR)
	cp $(FILES) $(LIB_DIR)
    
$(LIB_DIR):
	mkdir -p $@

    
